### PR TITLE
(feature) (types) git: allow user to specify whether or not to check for untracked files

### PR DESCRIPTION
**Pull request by lucymhdavies**
Example output from bork status:
```
conflict (unresolvable): github /Users/lucy.davinhart/git_src/dev_utils_private lucymhdavies/dev_utils_private --branch=main --ssh --untracked-files=normal
local git repository has untracked files
```

Fixes https://github.com/skylarmacdonald/bork/issues/27

### CODE REVIEW

**Comment by skylarmacdonald** [comment]
Thank you for this! Would you also be able to add some documentation of the change in [`docs/_types/git.md`](https://github.com/skylarmacdonald/bork/blob/main/docs/_types/git.md)? And the tests, of course, though it looks like I will need to change the `bats` job to use the new repo.

**Review by skylarmacdonald — APPROVED** [review]

**Comment by skylarmacdonald** [comment]
ignore that... wrong button...

**Comment by skylarmacdonald** [comment]
Thanks for writing the test! If I can get the tests to pass locally I'll merge, depending how long it takes me to fix the CI.

**Comment by skylarmacdonald** [comment]
cheeky merge into your branch now I've fixed the CI 😎 I think the tests may fail though... this is what I get on my machine:
```
 ✗ git status: returns CONFLICT_UPGRADE when the local git repository is ahead
   (in test file test/type-git.bats, line 64)
     `[ "$status" -eq $STATUS_CONFLICT_UPGRADE ]' failed with status 13
 ✗ git status: returns CONFLICT_UPGRADE when the local git repository has unstaged changes
   (in test file test/type-git.bats, line 71)
     `[ "$status" -eq $STATUS_CONFLICT_UPGRADE ]' failed with status 13
 ✗ git status: returns CONFLICT_UPGRADE when local git repository has uncommitted staged changes
   (in test file test/type-git.bats, line 78)
     `[ "$status" -eq $STATUS_CONFLICT_UPGRADE ]' failed with status 13
 ✗ git status: returns OUTDATED when the local git repository is known to be behind
   (in test file test/type-git.bats, line 85)
     `[ "$status" -eq $STATUS_OUTDATED ]' failed with status 13
 ✗ git status: returns CONFLICT_HALT when local git repository has untracked files
   (in test file test/type-git.bats, line 91)
     `[ "$status" -eq $STATUS_CONFLICT_HALT ]' failed with status 13
 ✗ git status: returns OK when the git repository is up-to-date
   (in test file test/type-git.bats, line 98)
     `[ "$status" -eq $STATUS_OK ]' failed with status 13
 ✗ git status: returns OK with directory argument and repo is current
   (in test file test/type-git.bats, line 106)
     `[ "$status" -eq $STATUS_OK ]' failed with status 13
```

**Comment by skylarmacdonald** [comment]
yep, same in CI I'm afraid... [see log here](https://github.com/skylarmacdonald/bork/pull/28/checks?check_run_id=3184966393#step:5:159)

**Comment by lucymhdavies** [comment]
I see 🤔

I’ll have to look into why that is later.

**Comment by skylarmacdonald** [comment]
There you go — simple fix, the stubbed `git` command needed changing in the test.

**Review by skylarmacdonald — APPROVED** [review]

**Pull request merged**
